/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyPartnerRouteImport } from './routes/verify-partner'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SignupPartnerRouteImport } from './routes/signup-partner'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountTypeRouteImport } from './routes/account-type'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as PartnersRouteRouteImport } from './routes/partners/route'
import { Route as InvestorsRouteRouteImport } from './routes/investors/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecoverPasswordIndexRouteImport } from './routes/recover-password/index'
import { Route as PartnersIndexRouteImport } from './routes/partners/index'
import { Route as InvestorsIndexRouteImport } from './routes/investors/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CoporateIndexRouteImport } from './routes/coporate/index'
import { Route as PartnersTransactionsRouteImport } from './routes/partners/transactions'
import { Route as PartnersSettingsRouteImport } from './routes/partners/settings'
import { Route as PartnersPropertiesRouteImport } from './routes/partners/properties'
import { Route as PartnersNotificationsRouteImport } from './routes/partners/notifications'
import { Route as PartnersMyInvestmentsRouteImport } from './routes/partners/my-investments'
import { Route as PartnersAnnouncementsRouteImport } from './routes/partners/announcements'
import { Route as InvestorsTransactionsRouteImport } from './routes/investors/transactions'
import { Route as InvestorsSettingsRouteImport } from './routes/investors/settings'
import { Route as InvestorsPropertiesRouteImport } from './routes/investors/properties'
import { Route as InvestorsNotificationsRouteImport } from './routes/investors/notifications'
import { Route as InvestorsMyInvestmentsRouteImport } from './routes/investors/my-investments'
import { Route as InvestorsAnnouncementsRouteImport } from './routes/investors/announcements'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPartnersRouteImport } from './routes/dashboard/partners'
import { Route as DashboardInvestorsRouteImport } from './routes/dashboard/investors'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard/announcements'
import { Route as DashboardVerificationsRouteRouteImport } from './routes/dashboard/verifications/route'
import { Route as ForgotPasswordResetIndexRouteImport } from './routes/forgot-password/reset/index'
import { Route as DashboardVerificationsIndexRouteImport } from './routes/dashboard/verifications/index'
import { Route as DashboardPartnersIndexRouteImport } from './routes/dashboard/partners/index'
import { Route as DashboardInvestorsIndexRouteImport } from './routes/dashboard/investors/index'
import { Route as PartnersPropertiesPropertyIdRouteImport } from './routes/partners/properties/$propertyId'
import { Route as InvestorsPropertiesPropertyIdRouteImport } from './routes/investors/properties/$propertyId'
import { Route as DashboardTransactionsReceiptsRouteImport } from './routes/dashboard/transactions/receipts'
import { Route as DashboardTransactionsPaymentsRouteImport } from './routes/dashboard/transactions/payments'
import { Route as DashboardPropertiesNewRouteImport } from './routes/dashboard/properties/new'
import { Route as DashboardPropertiesListedRouteImport } from './routes/dashboard/properties/listed'
import { Route as DashboardPropertiesPropertyIdRouteImport } from './routes/dashboard/properties/$propertyId'
import { Route as DashboardPartnersPartnerIdRouteImport } from './routes/dashboard/partners/$partnerId'
import { Route as DashboardInvestorsInvestorIdRouteImport } from './routes/dashboard/investors/$investorId'
import { Route as PartnerRecoverForgotPasswordIndexRouteImport } from './routes/partner/recover/forgot-password/index'
import { Route as DashboardPropertiesPropertyIdIndexRouteImport } from './routes/dashboard/properties/$propertyId/index'
import { Route as DashboardPartnersPartnerIdIndexRouteImport } from './routes/dashboard/partners/$partnerId/index'
import { Route as DashboardInvestorsCorporateIndexRouteImport } from './routes/dashboard/investors/corporate/index'
import { Route as DashboardInvestorsInvestorIdIndexRouteImport } from './routes/dashboard/investors/$investorId/index'
import { Route as DashboardPropertiesPropertyIdEditRouteImport } from './routes/dashboard/properties/$propertyId/edit'
import { Route as DashboardPartnersPartnerIdKycRouteImport } from './routes/dashboard/partners/$partnerId/kyc'
import { Route as DashboardInvestorsInvestorIdKycRouteImport } from './routes/dashboard/investors/$investorId/kyc'
import { Route as PartnerRecoverForgotPasswordResetIndexRouteImport } from './routes/partner/recover/forgot-password/reset/index'

const VerifyPartnerRoute = VerifyPartnerRouteImport.update({
  id: '/verify-partner',
  path: '/verify-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPartnerRoute = SignupPartnerRouteImport.update({
  id: '/signup-partner',
  path: '/signup-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTypeRoute = AccountTypeRouteImport.update({
  id: '/account-type',
  path: '/account-type',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRouteRoute = PartnersRouteRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRouteRoute = InvestorsRouteRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordIndexRoute = RecoverPasswordIndexRouteImport.update({
  id: '/recover-password/',
  path: '/recover-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnersRouteRoute,
} as any)
const InvestorsIndexRoute = InvestorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestorsRouteRoute,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CoporateIndexRoute = CoporateIndexRouteImport.update({
  id: '/coporate/',
  path: '/coporate/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersTransactionsRoute = PartnersTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PartnersRouteRoute,
} as any)
const PartnersSettingsRoute = PartnersSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PartnersRouteRoute,
} as any)
const PartnersPropertiesRoute = PartnersPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => PartnersRouteRoute,
} as any)
const PartnersNotificationsRoute = PartnersNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PartnersRouteRoute,
} as any)
const PartnersMyInvestmentsRoute = PartnersMyInvestmentsRouteImport.update({
  id: '/my-investments',
  path: '/my-investments',
  getParentRoute: () => PartnersRouteRoute,
} as any)
const PartnersAnnouncementsRoute = PartnersAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => PartnersRouteRoute,
} as any)
const InvestorsTransactionsRoute = InvestorsTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => InvestorsRouteRoute,
} as any)
const InvestorsSettingsRoute = InvestorsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InvestorsRouteRoute,
} as any)
const InvestorsPropertiesRoute = InvestorsPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => InvestorsRouteRoute,
} as any)
const InvestorsNotificationsRoute = InvestorsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => InvestorsRouteRoute,
} as any)
const InvestorsMyInvestmentsRoute = InvestorsMyInvestmentsRouteImport.update({
  id: '/my-investments',
  path: '/my-investments',
  getParentRoute: () => InvestorsRouteRoute,
} as any)
const InvestorsAnnouncementsRoute = InvestorsAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => InvestorsRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPartnersRoute = DashboardPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvestorsRoute = DashboardInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardVerificationsRouteRoute =
  DashboardVerificationsRouteRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ForgotPasswordResetIndexRoute =
  ForgotPasswordResetIndexRouteImport.update({
    id: '/forgot-password/reset/',
    path: '/forgot-password/reset/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardVerificationsIndexRoute =
  DashboardVerificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardVerificationsRouteRoute,
  } as any)
const DashboardPartnersIndexRoute = DashboardPartnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPartnersRoute,
} as any)
const DashboardInvestorsIndexRoute = DashboardInvestorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInvestorsRoute,
} as any)
const PartnersPropertiesPropertyIdRoute =
  PartnersPropertiesPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => PartnersPropertiesRoute,
  } as any)
const InvestorsPropertiesPropertyIdRoute =
  InvestorsPropertiesPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => InvestorsPropertiesRoute,
  } as any)
const DashboardTransactionsReceiptsRoute =
  DashboardTransactionsReceiptsRouteImport.update({
    id: '/transactions/receipts',
    path: '/transactions/receipts',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTransactionsPaymentsRoute =
  DashboardTransactionsPaymentsRouteImport.update({
    id: '/transactions/payments',
    path: '/transactions/payments',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPropertiesNewRoute = DashboardPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPropertiesListedRoute =
  DashboardPropertiesListedRouteImport.update({
    id: '/properties/listed',
    path: '/properties/listed',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPropertiesPropertyIdRoute =
  DashboardPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPartnersPartnerIdRoute =
  DashboardPartnersPartnerIdRouteImport.update({
    id: '/$partnerId',
    path: '/$partnerId',
    getParentRoute: () => DashboardPartnersRoute,
  } as any)
const DashboardInvestorsInvestorIdRoute =
  DashboardInvestorsInvestorIdRouteImport.update({
    id: '/$investorId',
    path: '/$investorId',
    getParentRoute: () => DashboardInvestorsRoute,
  } as any)
const PartnerRecoverForgotPasswordIndexRoute =
  PartnerRecoverForgotPasswordIndexRouteImport.update({
    id: '/partner/recover/forgot-password/',
    path: '/partner/recover/forgot-password/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPropertiesPropertyIdIndexRoute =
  DashboardPropertiesPropertyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPropertiesPropertyIdRoute,
  } as any)
const DashboardPartnersPartnerIdIndexRoute =
  DashboardPartnersPartnerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPartnersPartnerIdRoute,
  } as any)
const DashboardInvestorsCorporateIndexRoute =
  DashboardInvestorsCorporateIndexRouteImport.update({
    id: '/corporate/',
    path: '/corporate/',
    getParentRoute: () => DashboardInvestorsRoute,
  } as any)
const DashboardInvestorsInvestorIdIndexRoute =
  DashboardInvestorsInvestorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInvestorsInvestorIdRoute,
  } as any)
const DashboardPropertiesPropertyIdEditRoute =
  DashboardPropertiesPropertyIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardPropertiesPropertyIdRoute,
  } as any)
const DashboardPartnersPartnerIdKycRoute =
  DashboardPartnersPartnerIdKycRouteImport.update({
    id: '/kyc',
    path: '/kyc',
    getParentRoute: () => DashboardPartnersPartnerIdRoute,
  } as any)
const DashboardInvestorsInvestorIdKycRoute =
  DashboardInvestorsInvestorIdKycRouteImport.update({
    id: '/kyc',
    path: '/kyc',
    getParentRoute: () => DashboardInvestorsInvestorIdRoute,
  } as any)
const PartnerRecoverForgotPasswordResetIndexRoute =
  PartnerRecoverForgotPasswordResetIndexRouteImport.update({
    id: '/partner/recover/forgot-password/reset/',
    path: '/partner/recover/forgot-password/reset/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/investors': typeof InvestorsRouteRouteWithChildren
  '/partners': typeof PartnersRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/account-type': typeof AccountTypeRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/faqs': typeof FaqsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/otp': typeof OtpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/signup-partner': typeof SignupPartnerRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/verify-partner': typeof VerifyPartnerRoute
  '/dashboard/verifications': typeof DashboardVerificationsRouteRouteWithChildren
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/investors': typeof DashboardInvestorsRouteWithChildren
  '/dashboard/partners': typeof DashboardPartnersRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/investors/announcements': typeof InvestorsAnnouncementsRoute
  '/investors/my-investments': typeof InvestorsMyInvestmentsRoute
  '/investors/notifications': typeof InvestorsNotificationsRoute
  '/investors/properties': typeof InvestorsPropertiesRouteWithChildren
  '/investors/settings': typeof InvestorsSettingsRoute
  '/investors/transactions': typeof InvestorsTransactionsRoute
  '/partners/announcements': typeof PartnersAnnouncementsRoute
  '/partners/my-investments': typeof PartnersMyInvestmentsRoute
  '/partners/notifications': typeof PartnersNotificationsRoute
  '/partners/properties': typeof PartnersPropertiesRouteWithChildren
  '/partners/settings': typeof PartnersSettingsRoute
  '/partners/transactions': typeof PartnersTransactionsRoute
  '/coporate/': typeof CoporateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/investors/': typeof InvestorsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/recover-password/': typeof RecoverPasswordIndexRoute
  '/dashboard/investors/$investorId': typeof DashboardInvestorsInvestorIdRouteWithChildren
  '/dashboard/partners/$partnerId': typeof DashboardPartnersPartnerIdRouteWithChildren
  '/dashboard/properties/$propertyId': typeof DashboardPropertiesPropertyIdRouteWithChildren
  '/dashboard/properties/listed': typeof DashboardPropertiesListedRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/dashboard/transactions/payments': typeof DashboardTransactionsPaymentsRoute
  '/dashboard/transactions/receipts': typeof DashboardTransactionsReceiptsRoute
  '/investors/properties/$propertyId': typeof InvestorsPropertiesPropertyIdRoute
  '/partners/properties/$propertyId': typeof PartnersPropertiesPropertyIdRoute
  '/dashboard/investors/': typeof DashboardInvestorsIndexRoute
  '/dashboard/partners/': typeof DashboardPartnersIndexRoute
  '/dashboard/verifications/': typeof DashboardVerificationsIndexRoute
  '/forgot-password/reset/': typeof ForgotPasswordResetIndexRoute
  '/dashboard/investors/$investorId/kyc': typeof DashboardInvestorsInvestorIdKycRoute
  '/dashboard/partners/$partnerId/kyc': typeof DashboardPartnersPartnerIdKycRoute
  '/dashboard/properties/$propertyId/edit': typeof DashboardPropertiesPropertyIdEditRoute
  '/dashboard/investors/$investorId/': typeof DashboardInvestorsInvestorIdIndexRoute
  '/dashboard/investors/corporate/': typeof DashboardInvestorsCorporateIndexRoute
  '/dashboard/partners/$partnerId/': typeof DashboardPartnersPartnerIdIndexRoute
  '/dashboard/properties/$propertyId/': typeof DashboardPropertiesPropertyIdIndexRoute
  '/partner/recover/forgot-password/': typeof PartnerRecoverForgotPasswordIndexRoute
  '/partner/recover/forgot-password/reset/': typeof PartnerRecoverForgotPasswordResetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account-type': typeof AccountTypeRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/faqs': typeof FaqsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/otp': typeof OtpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/signup-partner': typeof SignupPartnerRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/verify-partner': typeof VerifyPartnerRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/investors/announcements': typeof InvestorsAnnouncementsRoute
  '/investors/my-investments': typeof InvestorsMyInvestmentsRoute
  '/investors/notifications': typeof InvestorsNotificationsRoute
  '/investors/properties': typeof InvestorsPropertiesRouteWithChildren
  '/investors/settings': typeof InvestorsSettingsRoute
  '/investors/transactions': typeof InvestorsTransactionsRoute
  '/partners/announcements': typeof PartnersAnnouncementsRoute
  '/partners/my-investments': typeof PartnersMyInvestmentsRoute
  '/partners/notifications': typeof PartnersNotificationsRoute
  '/partners/properties': typeof PartnersPropertiesRouteWithChildren
  '/partners/settings': typeof PartnersSettingsRoute
  '/partners/transactions': typeof PartnersTransactionsRoute
  '/coporate': typeof CoporateIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/investors': typeof InvestorsIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/recover-password': typeof RecoverPasswordIndexRoute
  '/dashboard/properties/listed': typeof DashboardPropertiesListedRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/dashboard/transactions/payments': typeof DashboardTransactionsPaymentsRoute
  '/dashboard/transactions/receipts': typeof DashboardTransactionsReceiptsRoute
  '/investors/properties/$propertyId': typeof InvestorsPropertiesPropertyIdRoute
  '/partners/properties/$propertyId': typeof PartnersPropertiesPropertyIdRoute
  '/dashboard/investors': typeof DashboardInvestorsIndexRoute
  '/dashboard/partners': typeof DashboardPartnersIndexRoute
  '/dashboard/verifications': typeof DashboardVerificationsIndexRoute
  '/forgot-password/reset': typeof ForgotPasswordResetIndexRoute
  '/dashboard/investors/$investorId/kyc': typeof DashboardInvestorsInvestorIdKycRoute
  '/dashboard/partners/$partnerId/kyc': typeof DashboardPartnersPartnerIdKycRoute
  '/dashboard/properties/$propertyId/edit': typeof DashboardPropertiesPropertyIdEditRoute
  '/dashboard/investors/$investorId': typeof DashboardInvestorsInvestorIdIndexRoute
  '/dashboard/investors/corporate': typeof DashboardInvestorsCorporateIndexRoute
  '/dashboard/partners/$partnerId': typeof DashboardPartnersPartnerIdIndexRoute
  '/dashboard/properties/$propertyId': typeof DashboardPropertiesPropertyIdIndexRoute
  '/partner/recover/forgot-password': typeof PartnerRecoverForgotPasswordIndexRoute
  '/partner/recover/forgot-password/reset': typeof PartnerRecoverForgotPasswordResetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/investors': typeof InvestorsRouteRouteWithChildren
  '/partners': typeof PartnersRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/account-type': typeof AccountTypeRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/faqs': typeof FaqsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/otp': typeof OtpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/signup-partner': typeof SignupPartnerRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/verify-partner': typeof VerifyPartnerRoute
  '/dashboard/verifications': typeof DashboardVerificationsRouteRouteWithChildren
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/investors': typeof DashboardInvestorsRouteWithChildren
  '/dashboard/partners': typeof DashboardPartnersRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/investors/announcements': typeof InvestorsAnnouncementsRoute
  '/investors/my-investments': typeof InvestorsMyInvestmentsRoute
  '/investors/notifications': typeof InvestorsNotificationsRoute
  '/investors/properties': typeof InvestorsPropertiesRouteWithChildren
  '/investors/settings': typeof InvestorsSettingsRoute
  '/investors/transactions': typeof InvestorsTransactionsRoute
  '/partners/announcements': typeof PartnersAnnouncementsRoute
  '/partners/my-investments': typeof PartnersMyInvestmentsRoute
  '/partners/notifications': typeof PartnersNotificationsRoute
  '/partners/properties': typeof PartnersPropertiesRouteWithChildren
  '/partners/settings': typeof PartnersSettingsRoute
  '/partners/transactions': typeof PartnersTransactionsRoute
  '/coporate/': typeof CoporateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/investors/': typeof InvestorsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/recover-password/': typeof RecoverPasswordIndexRoute
  '/dashboard/investors/$investorId': typeof DashboardInvestorsInvestorIdRouteWithChildren
  '/dashboard/partners/$partnerId': typeof DashboardPartnersPartnerIdRouteWithChildren
  '/dashboard/properties/$propertyId': typeof DashboardPropertiesPropertyIdRouteWithChildren
  '/dashboard/properties/listed': typeof DashboardPropertiesListedRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/dashboard/transactions/payments': typeof DashboardTransactionsPaymentsRoute
  '/dashboard/transactions/receipts': typeof DashboardTransactionsReceiptsRoute
  '/investors/properties/$propertyId': typeof InvestorsPropertiesPropertyIdRoute
  '/partners/properties/$propertyId': typeof PartnersPropertiesPropertyIdRoute
  '/dashboard/investors/': typeof DashboardInvestorsIndexRoute
  '/dashboard/partners/': typeof DashboardPartnersIndexRoute
  '/dashboard/verifications/': typeof DashboardVerificationsIndexRoute
  '/forgot-password/reset/': typeof ForgotPasswordResetIndexRoute
  '/dashboard/investors/$investorId/kyc': typeof DashboardInvestorsInvestorIdKycRoute
  '/dashboard/partners/$partnerId/kyc': typeof DashboardPartnersPartnerIdKycRoute
  '/dashboard/properties/$propertyId/edit': typeof DashboardPropertiesPropertyIdEditRoute
  '/dashboard/investors/$investorId/': typeof DashboardInvestorsInvestorIdIndexRoute
  '/dashboard/investors/corporate/': typeof DashboardInvestorsCorporateIndexRoute
  '/dashboard/partners/$partnerId/': typeof DashboardPartnersPartnerIdIndexRoute
  '/dashboard/properties/$propertyId/': typeof DashboardPropertiesPropertyIdIndexRoute
  '/partner/recover/forgot-password/': typeof PartnerRecoverForgotPasswordIndexRoute
  '/partner/recover/forgot-password/reset/': typeof PartnerRecoverForgotPasswordResetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/investors'
    | '/partners'
    | '/about-us'
    | '/account-type'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/contact-us'
    | '/faqs'
    | '/how-it-works'
    | '/leadership'
    | '/login'
    | '/news'
    | '/otp'
    | '/privacy-policy'
    | '/signup'
    | '/signup-partner'
    | '/terms-and-conditions'
    | '/test'
    | '/verify'
    | '/verify-partner'
    | '/dashboard/verifications'
    | '/dashboard/announcements'
    | '/dashboard/investors'
    | '/dashboard/partners'
    | '/dashboard/settings'
    | '/investors/announcements'
    | '/investors/my-investments'
    | '/investors/notifications'
    | '/investors/properties'
    | '/investors/settings'
    | '/investors/transactions'
    | '/partners/announcements'
    | '/partners/my-investments'
    | '/partners/notifications'
    | '/partners/properties'
    | '/partners/settings'
    | '/partners/transactions'
    | '/coporate/'
    | '/dashboard/'
    | '/forgot-password/'
    | '/investors/'
    | '/partners/'
    | '/recover-password/'
    | '/dashboard/investors/$investorId'
    | '/dashboard/partners/$partnerId'
    | '/dashboard/properties/$propertyId'
    | '/dashboard/properties/listed'
    | '/dashboard/properties/new'
    | '/dashboard/transactions/payments'
    | '/dashboard/transactions/receipts'
    | '/investors/properties/$propertyId'
    | '/partners/properties/$propertyId'
    | '/dashboard/investors/'
    | '/dashboard/partners/'
    | '/dashboard/verifications/'
    | '/forgot-password/reset/'
    | '/dashboard/investors/$investorId/kyc'
    | '/dashboard/partners/$partnerId/kyc'
    | '/dashboard/properties/$propertyId/edit'
    | '/dashboard/investors/$investorId/'
    | '/dashboard/investors/corporate/'
    | '/dashboard/partners/$partnerId/'
    | '/dashboard/properties/$propertyId/'
    | '/partner/recover/forgot-password/'
    | '/partner/recover/forgot-password/reset/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/account-type'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/contact-us'
    | '/faqs'
    | '/how-it-works'
    | '/leadership'
    | '/login'
    | '/news'
    | '/otp'
    | '/privacy-policy'
    | '/signup'
    | '/signup-partner'
    | '/terms-and-conditions'
    | '/test'
    | '/verify'
    | '/verify-partner'
    | '/dashboard/announcements'
    | '/dashboard/settings'
    | '/investors/announcements'
    | '/investors/my-investments'
    | '/investors/notifications'
    | '/investors/properties'
    | '/investors/settings'
    | '/investors/transactions'
    | '/partners/announcements'
    | '/partners/my-investments'
    | '/partners/notifications'
    | '/partners/properties'
    | '/partners/settings'
    | '/partners/transactions'
    | '/coporate'
    | '/dashboard'
    | '/forgot-password'
    | '/investors'
    | '/partners'
    | '/recover-password'
    | '/dashboard/properties/listed'
    | '/dashboard/properties/new'
    | '/dashboard/transactions/payments'
    | '/dashboard/transactions/receipts'
    | '/investors/properties/$propertyId'
    | '/partners/properties/$propertyId'
    | '/dashboard/investors'
    | '/dashboard/partners'
    | '/dashboard/verifications'
    | '/forgot-password/reset'
    | '/dashboard/investors/$investorId/kyc'
    | '/dashboard/partners/$partnerId/kyc'
    | '/dashboard/properties/$propertyId/edit'
    | '/dashboard/investors/$investorId'
    | '/dashboard/investors/corporate'
    | '/dashboard/partners/$partnerId'
    | '/dashboard/properties/$propertyId'
    | '/partner/recover/forgot-password'
    | '/partner/recover/forgot-password/reset'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/investors'
    | '/partners'
    | '/about-us'
    | '/account-type'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/contact-us'
    | '/faqs'
    | '/how-it-works'
    | '/leadership'
    | '/login'
    | '/news'
    | '/otp'
    | '/privacy-policy'
    | '/signup'
    | '/signup-partner'
    | '/terms-and-conditions'
    | '/test'
    | '/verify'
    | '/verify-partner'
    | '/dashboard/verifications'
    | '/dashboard/announcements'
    | '/dashboard/investors'
    | '/dashboard/partners'
    | '/dashboard/settings'
    | '/investors/announcements'
    | '/investors/my-investments'
    | '/investors/notifications'
    | '/investors/properties'
    | '/investors/settings'
    | '/investors/transactions'
    | '/partners/announcements'
    | '/partners/my-investments'
    | '/partners/notifications'
    | '/partners/properties'
    | '/partners/settings'
    | '/partners/transactions'
    | '/coporate/'
    | '/dashboard/'
    | '/forgot-password/'
    | '/investors/'
    | '/partners/'
    | '/recover-password/'
    | '/dashboard/investors/$investorId'
    | '/dashboard/partners/$partnerId'
    | '/dashboard/properties/$propertyId'
    | '/dashboard/properties/listed'
    | '/dashboard/properties/new'
    | '/dashboard/transactions/payments'
    | '/dashboard/transactions/receipts'
    | '/investors/properties/$propertyId'
    | '/partners/properties/$propertyId'
    | '/dashboard/investors/'
    | '/dashboard/partners/'
    | '/dashboard/verifications/'
    | '/forgot-password/reset/'
    | '/dashboard/investors/$investorId/kyc'
    | '/dashboard/partners/$partnerId/kyc'
    | '/dashboard/properties/$propertyId/edit'
    | '/dashboard/investors/$investorId/'
    | '/dashboard/investors/corporate/'
    | '/dashboard/partners/$partnerId/'
    | '/dashboard/properties/$propertyId/'
    | '/partner/recover/forgot-password/'
    | '/partner/recover/forgot-password/reset/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  InvestorsRouteRoute: typeof InvestorsRouteRouteWithChildren
  PartnersRouteRoute: typeof PartnersRouteRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  AccountTypeRoute: typeof AccountTypeRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactUsRoute: typeof ContactUsRoute
  FaqsRoute: typeof FaqsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LeadershipRoute: typeof LeadershipRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  OtpRoute: typeof OtpRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SignupRoute: typeof SignupRoute
  SignupPartnerRoute: typeof SignupPartnerRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TestRoute: typeof TestRoute
  VerifyRoute: typeof VerifyRoute
  VerifyPartnerRoute: typeof VerifyPartnerRoute
  CoporateIndexRoute: typeof CoporateIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  RecoverPasswordIndexRoute: typeof RecoverPasswordIndexRoute
  ForgotPasswordResetIndexRoute: typeof ForgotPasswordResetIndexRoute
  PartnerRecoverForgotPasswordIndexRoute: typeof PartnerRecoverForgotPasswordIndexRoute
  PartnerRecoverForgotPasswordResetIndexRoute: typeof PartnerRecoverForgotPasswordResetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-partner': {
      id: '/verify-partner'
      path: '/verify-partner'
      fullPath: '/verify-partner'
      preLoaderRoute: typeof VerifyPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-partner': {
      id: '/signup-partner'
      path: '/signup-partner'
      fullPath: '/signup-partner'
      preLoaderRoute: typeof SignupPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-type': {
      id: '/account-type'
      path: '/account-type'
      fullPath: '/account-type'
      preLoaderRoute: typeof AccountTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password/': {
      id: '/recover-password/'
      path: '/recover-password'
      fullPath: '/recover-password/'
      preLoaderRoute: typeof RecoverPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof PartnersRouteRoute
    }
    '/investors/': {
      id: '/investors/'
      path: '/'
      fullPath: '/investors/'
      preLoaderRoute: typeof InvestorsIndexRouteImport
      parentRoute: typeof InvestorsRouteRoute
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/coporate/': {
      id: '/coporate/'
      path: '/coporate'
      fullPath: '/coporate/'
      preLoaderRoute: typeof CoporateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/transactions': {
      id: '/partners/transactions'
      path: '/transactions'
      fullPath: '/partners/transactions'
      preLoaderRoute: typeof PartnersTransactionsRouteImport
      parentRoute: typeof PartnersRouteRoute
    }
    '/partners/settings': {
      id: '/partners/settings'
      path: '/settings'
      fullPath: '/partners/settings'
      preLoaderRoute: typeof PartnersSettingsRouteImport
      parentRoute: typeof PartnersRouteRoute
    }
    '/partners/properties': {
      id: '/partners/properties'
      path: '/properties'
      fullPath: '/partners/properties'
      preLoaderRoute: typeof PartnersPropertiesRouteImport
      parentRoute: typeof PartnersRouteRoute
    }
    '/partners/notifications': {
      id: '/partners/notifications'
      path: '/notifications'
      fullPath: '/partners/notifications'
      preLoaderRoute: typeof PartnersNotificationsRouteImport
      parentRoute: typeof PartnersRouteRoute
    }
    '/partners/my-investments': {
      id: '/partners/my-investments'
      path: '/my-investments'
      fullPath: '/partners/my-investments'
      preLoaderRoute: typeof PartnersMyInvestmentsRouteImport
      parentRoute: typeof PartnersRouteRoute
    }
    '/partners/announcements': {
      id: '/partners/announcements'
      path: '/announcements'
      fullPath: '/partners/announcements'
      preLoaderRoute: typeof PartnersAnnouncementsRouteImport
      parentRoute: typeof PartnersRouteRoute
    }
    '/investors/transactions': {
      id: '/investors/transactions'
      path: '/transactions'
      fullPath: '/investors/transactions'
      preLoaderRoute: typeof InvestorsTransactionsRouteImport
      parentRoute: typeof InvestorsRouteRoute
    }
    '/investors/settings': {
      id: '/investors/settings'
      path: '/settings'
      fullPath: '/investors/settings'
      preLoaderRoute: typeof InvestorsSettingsRouteImport
      parentRoute: typeof InvestorsRouteRoute
    }
    '/investors/properties': {
      id: '/investors/properties'
      path: '/properties'
      fullPath: '/investors/properties'
      preLoaderRoute: typeof InvestorsPropertiesRouteImport
      parentRoute: typeof InvestorsRouteRoute
    }
    '/investors/notifications': {
      id: '/investors/notifications'
      path: '/notifications'
      fullPath: '/investors/notifications'
      preLoaderRoute: typeof InvestorsNotificationsRouteImport
      parentRoute: typeof InvestorsRouteRoute
    }
    '/investors/my-investments': {
      id: '/investors/my-investments'
      path: '/my-investments'
      fullPath: '/investors/my-investments'
      preLoaderRoute: typeof InvestorsMyInvestmentsRouteImport
      parentRoute: typeof InvestorsRouteRoute
    }
    '/investors/announcements': {
      id: '/investors/announcements'
      path: '/announcements'
      fullPath: '/investors/announcements'
      preLoaderRoute: typeof InvestorsAnnouncementsRouteImport
      parentRoute: typeof InvestorsRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/partners': {
      id: '/dashboard/partners'
      path: '/partners'
      fullPath: '/dashboard/partners'
      preLoaderRoute: typeof DashboardPartnersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/investors': {
      id: '/dashboard/investors'
      path: '/investors'
      fullPath: '/dashboard/investors'
      preLoaderRoute: typeof DashboardInvestorsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/verifications': {
      id: '/dashboard/verifications'
      path: '/verifications'
      fullPath: '/dashboard/verifications'
      preLoaderRoute: typeof DashboardVerificationsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/forgot-password/reset/': {
      id: '/forgot-password/reset/'
      path: '/forgot-password/reset'
      fullPath: '/forgot-password/reset/'
      preLoaderRoute: typeof ForgotPasswordResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verifications/': {
      id: '/dashboard/verifications/'
      path: '/'
      fullPath: '/dashboard/verifications/'
      preLoaderRoute: typeof DashboardVerificationsIndexRouteImport
      parentRoute: typeof DashboardVerificationsRouteRoute
    }
    '/dashboard/partners/': {
      id: '/dashboard/partners/'
      path: '/'
      fullPath: '/dashboard/partners/'
      preLoaderRoute: typeof DashboardPartnersIndexRouteImport
      parentRoute: typeof DashboardPartnersRoute
    }
    '/dashboard/investors/': {
      id: '/dashboard/investors/'
      path: '/'
      fullPath: '/dashboard/investors/'
      preLoaderRoute: typeof DashboardInvestorsIndexRouteImport
      parentRoute: typeof DashboardInvestorsRoute
    }
    '/partners/properties/$propertyId': {
      id: '/partners/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/partners/properties/$propertyId'
      preLoaderRoute: typeof PartnersPropertiesPropertyIdRouteImport
      parentRoute: typeof PartnersPropertiesRoute
    }
    '/investors/properties/$propertyId': {
      id: '/investors/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/investors/properties/$propertyId'
      preLoaderRoute: typeof InvestorsPropertiesPropertyIdRouteImport
      parentRoute: typeof InvestorsPropertiesRoute
    }
    '/dashboard/transactions/receipts': {
      id: '/dashboard/transactions/receipts'
      path: '/transactions/receipts'
      fullPath: '/dashboard/transactions/receipts'
      preLoaderRoute: typeof DashboardTransactionsReceiptsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions/payments': {
      id: '/dashboard/transactions/payments'
      path: '/transactions/payments'
      fullPath: '/dashboard/transactions/payments'
      preLoaderRoute: typeof DashboardTransactionsPaymentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/properties/new': {
      id: '/dashboard/properties/new'
      path: '/properties/new'
      fullPath: '/dashboard/properties/new'
      preLoaderRoute: typeof DashboardPropertiesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/properties/listed': {
      id: '/dashboard/properties/listed'
      path: '/properties/listed'
      fullPath: '/dashboard/properties/listed'
      preLoaderRoute: typeof DashboardPropertiesListedRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/properties/$propertyId': {
      id: '/dashboard/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/dashboard/properties/$propertyId'
      preLoaderRoute: typeof DashboardPropertiesPropertyIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/partners/$partnerId': {
      id: '/dashboard/partners/$partnerId'
      path: '/$partnerId'
      fullPath: '/dashboard/partners/$partnerId'
      preLoaderRoute: typeof DashboardPartnersPartnerIdRouteImport
      parentRoute: typeof DashboardPartnersRoute
    }
    '/dashboard/investors/$investorId': {
      id: '/dashboard/investors/$investorId'
      path: '/$investorId'
      fullPath: '/dashboard/investors/$investorId'
      preLoaderRoute: typeof DashboardInvestorsInvestorIdRouteImport
      parentRoute: typeof DashboardInvestorsRoute
    }
    '/partner/recover/forgot-password/': {
      id: '/partner/recover/forgot-password/'
      path: '/partner/recover/forgot-password'
      fullPath: '/partner/recover/forgot-password/'
      preLoaderRoute: typeof PartnerRecoverForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/properties/$propertyId/': {
      id: '/dashboard/properties/$propertyId/'
      path: '/'
      fullPath: '/dashboard/properties/$propertyId/'
      preLoaderRoute: typeof DashboardPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof DashboardPropertiesPropertyIdRoute
    }
    '/dashboard/partners/$partnerId/': {
      id: '/dashboard/partners/$partnerId/'
      path: '/'
      fullPath: '/dashboard/partners/$partnerId/'
      preLoaderRoute: typeof DashboardPartnersPartnerIdIndexRouteImport
      parentRoute: typeof DashboardPartnersPartnerIdRoute
    }
    '/dashboard/investors/corporate/': {
      id: '/dashboard/investors/corporate/'
      path: '/corporate'
      fullPath: '/dashboard/investors/corporate/'
      preLoaderRoute: typeof DashboardInvestorsCorporateIndexRouteImport
      parentRoute: typeof DashboardInvestorsRoute
    }
    '/dashboard/investors/$investorId/': {
      id: '/dashboard/investors/$investorId/'
      path: '/'
      fullPath: '/dashboard/investors/$investorId/'
      preLoaderRoute: typeof DashboardInvestorsInvestorIdIndexRouteImport
      parentRoute: typeof DashboardInvestorsInvestorIdRoute
    }
    '/dashboard/properties/$propertyId/edit': {
      id: '/dashboard/properties/$propertyId/edit'
      path: '/edit'
      fullPath: '/dashboard/properties/$propertyId/edit'
      preLoaderRoute: typeof DashboardPropertiesPropertyIdEditRouteImport
      parentRoute: typeof DashboardPropertiesPropertyIdRoute
    }
    '/dashboard/partners/$partnerId/kyc': {
      id: '/dashboard/partners/$partnerId/kyc'
      path: '/kyc'
      fullPath: '/dashboard/partners/$partnerId/kyc'
      preLoaderRoute: typeof DashboardPartnersPartnerIdKycRouteImport
      parentRoute: typeof DashboardPartnersPartnerIdRoute
    }
    '/dashboard/investors/$investorId/kyc': {
      id: '/dashboard/investors/$investorId/kyc'
      path: '/kyc'
      fullPath: '/dashboard/investors/$investorId/kyc'
      preLoaderRoute: typeof DashboardInvestorsInvestorIdKycRouteImport
      parentRoute: typeof DashboardInvestorsInvestorIdRoute
    }
    '/partner/recover/forgot-password/reset/': {
      id: '/partner/recover/forgot-password/reset/'
      path: '/partner/recover/forgot-password/reset'
      fullPath: '/partner/recover/forgot-password/reset/'
      preLoaderRoute: typeof PartnerRecoverForgotPasswordResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardVerificationsRouteRouteChildren {
  DashboardVerificationsIndexRoute: typeof DashboardVerificationsIndexRoute
}

const DashboardVerificationsRouteRouteChildren: DashboardVerificationsRouteRouteChildren =
  {
    DashboardVerificationsIndexRoute: DashboardVerificationsIndexRoute,
  }

const DashboardVerificationsRouteRouteWithChildren =
  DashboardVerificationsRouteRoute._addFileChildren(
    DashboardVerificationsRouteRouteChildren,
  )

interface DashboardInvestorsInvestorIdRouteChildren {
  DashboardInvestorsInvestorIdKycRoute: typeof DashboardInvestorsInvestorIdKycRoute
  DashboardInvestorsInvestorIdIndexRoute: typeof DashboardInvestorsInvestorIdIndexRoute
}

const DashboardInvestorsInvestorIdRouteChildren: DashboardInvestorsInvestorIdRouteChildren =
  {
    DashboardInvestorsInvestorIdKycRoute: DashboardInvestorsInvestorIdKycRoute,
    DashboardInvestorsInvestorIdIndexRoute:
      DashboardInvestorsInvestorIdIndexRoute,
  }

const DashboardInvestorsInvestorIdRouteWithChildren =
  DashboardInvestorsInvestorIdRoute._addFileChildren(
    DashboardInvestorsInvestorIdRouteChildren,
  )

interface DashboardInvestorsRouteChildren {
  DashboardInvestorsInvestorIdRoute: typeof DashboardInvestorsInvestorIdRouteWithChildren
  DashboardInvestorsIndexRoute: typeof DashboardInvestorsIndexRoute
  DashboardInvestorsCorporateIndexRoute: typeof DashboardInvestorsCorporateIndexRoute
}

const DashboardInvestorsRouteChildren: DashboardInvestorsRouteChildren = {
  DashboardInvestorsInvestorIdRoute:
    DashboardInvestorsInvestorIdRouteWithChildren,
  DashboardInvestorsIndexRoute: DashboardInvestorsIndexRoute,
  DashboardInvestorsCorporateIndexRoute: DashboardInvestorsCorporateIndexRoute,
}

const DashboardInvestorsRouteWithChildren =
  DashboardInvestorsRoute._addFileChildren(DashboardInvestorsRouteChildren)

interface DashboardPartnersPartnerIdRouteChildren {
  DashboardPartnersPartnerIdKycRoute: typeof DashboardPartnersPartnerIdKycRoute
  DashboardPartnersPartnerIdIndexRoute: typeof DashboardPartnersPartnerIdIndexRoute
}

const DashboardPartnersPartnerIdRouteChildren: DashboardPartnersPartnerIdRouteChildren =
  {
    DashboardPartnersPartnerIdKycRoute: DashboardPartnersPartnerIdKycRoute,
    DashboardPartnersPartnerIdIndexRoute: DashboardPartnersPartnerIdIndexRoute,
  }

const DashboardPartnersPartnerIdRouteWithChildren =
  DashboardPartnersPartnerIdRoute._addFileChildren(
    DashboardPartnersPartnerIdRouteChildren,
  )

interface DashboardPartnersRouteChildren {
  DashboardPartnersPartnerIdRoute: typeof DashboardPartnersPartnerIdRouteWithChildren
  DashboardPartnersIndexRoute: typeof DashboardPartnersIndexRoute
}

const DashboardPartnersRouteChildren: DashboardPartnersRouteChildren = {
  DashboardPartnersPartnerIdRoute: DashboardPartnersPartnerIdRouteWithChildren,
  DashboardPartnersIndexRoute: DashboardPartnersIndexRoute,
}

const DashboardPartnersRouteWithChildren =
  DashboardPartnersRoute._addFileChildren(DashboardPartnersRouteChildren)

interface DashboardPropertiesPropertyIdRouteChildren {
  DashboardPropertiesPropertyIdEditRoute: typeof DashboardPropertiesPropertyIdEditRoute
  DashboardPropertiesPropertyIdIndexRoute: typeof DashboardPropertiesPropertyIdIndexRoute
}

const DashboardPropertiesPropertyIdRouteChildren: DashboardPropertiesPropertyIdRouteChildren =
  {
    DashboardPropertiesPropertyIdEditRoute:
      DashboardPropertiesPropertyIdEditRoute,
    DashboardPropertiesPropertyIdIndexRoute:
      DashboardPropertiesPropertyIdIndexRoute,
  }

const DashboardPropertiesPropertyIdRouteWithChildren =
  DashboardPropertiesPropertyIdRoute._addFileChildren(
    DashboardPropertiesPropertyIdRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardVerificationsRouteRoute: typeof DashboardVerificationsRouteRouteWithChildren
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardInvestorsRoute: typeof DashboardInvestorsRouteWithChildren
  DashboardPartnersRoute: typeof DashboardPartnersRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPropertiesPropertyIdRoute: typeof DashboardPropertiesPropertyIdRouteWithChildren
  DashboardPropertiesListedRoute: typeof DashboardPropertiesListedRoute
  DashboardPropertiesNewRoute: typeof DashboardPropertiesNewRoute
  DashboardTransactionsPaymentsRoute: typeof DashboardTransactionsPaymentsRoute
  DashboardTransactionsReceiptsRoute: typeof DashboardTransactionsReceiptsRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardVerificationsRouteRoute:
    DashboardVerificationsRouteRouteWithChildren,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardInvestorsRoute: DashboardInvestorsRouteWithChildren,
  DashboardPartnersRoute: DashboardPartnersRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPropertiesPropertyIdRoute:
    DashboardPropertiesPropertyIdRouteWithChildren,
  DashboardPropertiesListedRoute: DashboardPropertiesListedRoute,
  DashboardPropertiesNewRoute: DashboardPropertiesNewRoute,
  DashboardTransactionsPaymentsRoute: DashboardTransactionsPaymentsRoute,
  DashboardTransactionsReceiptsRoute: DashboardTransactionsReceiptsRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface InvestorsPropertiesRouteChildren {
  InvestorsPropertiesPropertyIdRoute: typeof InvestorsPropertiesPropertyIdRoute
}

const InvestorsPropertiesRouteChildren: InvestorsPropertiesRouteChildren = {
  InvestorsPropertiesPropertyIdRoute: InvestorsPropertiesPropertyIdRoute,
}

const InvestorsPropertiesRouteWithChildren =
  InvestorsPropertiesRoute._addFileChildren(InvestorsPropertiesRouteChildren)

interface InvestorsRouteRouteChildren {
  InvestorsAnnouncementsRoute: typeof InvestorsAnnouncementsRoute
  InvestorsMyInvestmentsRoute: typeof InvestorsMyInvestmentsRoute
  InvestorsNotificationsRoute: typeof InvestorsNotificationsRoute
  InvestorsPropertiesRoute: typeof InvestorsPropertiesRouteWithChildren
  InvestorsSettingsRoute: typeof InvestorsSettingsRoute
  InvestorsTransactionsRoute: typeof InvestorsTransactionsRoute
  InvestorsIndexRoute: typeof InvestorsIndexRoute
}

const InvestorsRouteRouteChildren: InvestorsRouteRouteChildren = {
  InvestorsAnnouncementsRoute: InvestorsAnnouncementsRoute,
  InvestorsMyInvestmentsRoute: InvestorsMyInvestmentsRoute,
  InvestorsNotificationsRoute: InvestorsNotificationsRoute,
  InvestorsPropertiesRoute: InvestorsPropertiesRouteWithChildren,
  InvestorsSettingsRoute: InvestorsSettingsRoute,
  InvestorsTransactionsRoute: InvestorsTransactionsRoute,
  InvestorsIndexRoute: InvestorsIndexRoute,
}

const InvestorsRouteRouteWithChildren = InvestorsRouteRoute._addFileChildren(
  InvestorsRouteRouteChildren,
)

interface PartnersPropertiesRouteChildren {
  PartnersPropertiesPropertyIdRoute: typeof PartnersPropertiesPropertyIdRoute
}

const PartnersPropertiesRouteChildren: PartnersPropertiesRouteChildren = {
  PartnersPropertiesPropertyIdRoute: PartnersPropertiesPropertyIdRoute,
}

const PartnersPropertiesRouteWithChildren =
  PartnersPropertiesRoute._addFileChildren(PartnersPropertiesRouteChildren)

interface PartnersRouteRouteChildren {
  PartnersAnnouncementsRoute: typeof PartnersAnnouncementsRoute
  PartnersMyInvestmentsRoute: typeof PartnersMyInvestmentsRoute
  PartnersNotificationsRoute: typeof PartnersNotificationsRoute
  PartnersPropertiesRoute: typeof PartnersPropertiesRouteWithChildren
  PartnersSettingsRoute: typeof PartnersSettingsRoute
  PartnersTransactionsRoute: typeof PartnersTransactionsRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
}

const PartnersRouteRouteChildren: PartnersRouteRouteChildren = {
  PartnersAnnouncementsRoute: PartnersAnnouncementsRoute,
  PartnersMyInvestmentsRoute: PartnersMyInvestmentsRoute,
  PartnersNotificationsRoute: PartnersNotificationsRoute,
  PartnersPropertiesRoute: PartnersPropertiesRouteWithChildren,
  PartnersSettingsRoute: PartnersSettingsRoute,
  PartnersTransactionsRoute: PartnersTransactionsRoute,
  PartnersIndexRoute: PartnersIndexRoute,
}

const PartnersRouteRouteWithChildren = PartnersRouteRoute._addFileChildren(
  PartnersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  InvestorsRouteRoute: InvestorsRouteRouteWithChildren,
  PartnersRouteRoute: PartnersRouteRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  AccountTypeRoute: AccountTypeRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactUsRoute: ContactUsRoute,
  FaqsRoute: FaqsRoute,
  HowItWorksRoute: HowItWorksRoute,
  LeadershipRoute: LeadershipRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  OtpRoute: OtpRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SignupRoute: SignupRoute,
  SignupPartnerRoute: SignupPartnerRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TestRoute: TestRoute,
  VerifyRoute: VerifyRoute,
  VerifyPartnerRoute: VerifyPartnerRoute,
  CoporateIndexRoute: CoporateIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  RecoverPasswordIndexRoute: RecoverPasswordIndexRoute,
  ForgotPasswordResetIndexRoute: ForgotPasswordResetIndexRoute,
  PartnerRecoverForgotPasswordIndexRoute:
    PartnerRecoverForgotPasswordIndexRoute,
  PartnerRecoverForgotPasswordResetIndexRoute:
    PartnerRecoverForgotPasswordResetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
