/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TestRouteImport } from './routes/test'
import { Route as SignupPartnerRouteImport } from './routes/signup-partner'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountTypeRouteImport } from './routes/account-type'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestorsIndexRouteImport } from './routes/investors/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as InvestorsPropertiesRouteImport } from './routes/investors/properties'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPartnersRouteImport } from './routes/dashboard/partners'
import { Route as DashboardInvestorsRouteImport } from './routes/dashboard/investors'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard/announcements'
import { Route as ForgotPasswordResetIndexRouteImport } from './routes/forgot-password/reset/index'
import { Route as DashboardPartnersIndexRouteImport } from './routes/dashboard/partners/index'
import { Route as DashboardInvestorsIndexRouteImport } from './routes/dashboard/investors/index'
import { Route as DashboardTransactionsReceiptsRouteImport } from './routes/dashboard/transactions/receipts'
import { Route as DashboardTransactionsPaymentsRouteImport } from './routes/dashboard/transactions/payments'
import { Route as DashboardPropertiesNewRouteImport } from './routes/dashboard/properties/new'
import { Route as DashboardPropertiesListedRouteImport } from './routes/dashboard/properties/listed'
import { Route as DashboardPropertiesPropertyIdRouteImport } from './routes/dashboard/properties/$propertyId'
import { Route as DashboardPartnersPartnerIdRouteImport } from './routes/dashboard/partners/$partnerId'
import { Route as DashboardInvestorsInvestorIdRouteImport } from './routes/dashboard/investors/$investorId'
import { Route as DashboardPropertiesPropertyIdIndexRouteImport } from './routes/dashboard/properties/$propertyId/index'
import { Route as DashboardPartnersPartnerIdIndexRouteImport } from './routes/dashboard/partners/$partnerId/index'
import { Route as DashboardInvestorsInvestorIdIndexRouteImport } from './routes/dashboard/investors/$investorId/index'
import { Route as DashboardPropertiesPropertyIdEditRouteImport } from './routes/dashboard/properties/$propertyId/edit'
import { Route as DashboardPartnersPartnerIdKycRouteImport } from './routes/dashboard/partners/$partnerId/kyc'
import { Route as DashboardInvestorsInvestorIdKycRouteImport } from './routes/dashboard/investors/$investorId/kyc'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPartnerRoute = SignupPartnerRouteImport.update({
  id: '/signup-partner',
  path: '/signup-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTypeRoute = AccountTypeRouteImport.update({
  id: '/account-type',
  path: '/account-type',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsIndexRoute = InvestorsIndexRouteImport.update({
  id: '/investors/',
  path: '/investors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const InvestorsPropertiesRoute = InvestorsPropertiesRouteImport.update({
  id: '/investors/properties',
  path: '/investors/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPartnersRoute = DashboardPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvestorsRoute = DashboardInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ForgotPasswordResetIndexRoute =
  ForgotPasswordResetIndexRouteImport.update({
    id: '/forgot-password/reset/',
    path: '/forgot-password/reset/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPartnersIndexRoute = DashboardPartnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPartnersRoute,
} as any)
const DashboardInvestorsIndexRoute = DashboardInvestorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInvestorsRoute,
} as any)
const DashboardTransactionsReceiptsRoute =
  DashboardTransactionsReceiptsRouteImport.update({
    id: '/transactions/receipts',
    path: '/transactions/receipts',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTransactionsPaymentsRoute =
  DashboardTransactionsPaymentsRouteImport.update({
    id: '/transactions/payments',
    path: '/transactions/payments',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPropertiesNewRoute = DashboardPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPropertiesListedRoute =
  DashboardPropertiesListedRouteImport.update({
    id: '/properties/listed',
    path: '/properties/listed',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPropertiesPropertyIdRoute =
  DashboardPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPartnersPartnerIdRoute =
  DashboardPartnersPartnerIdRouteImport.update({
    id: '/$partnerId',
    path: '/$partnerId',
    getParentRoute: () => DashboardPartnersRoute,
  } as any)
const DashboardInvestorsInvestorIdRoute =
  DashboardInvestorsInvestorIdRouteImport.update({
    id: '/$investorId',
    path: '/$investorId',
    getParentRoute: () => DashboardInvestorsRoute,
  } as any)
const DashboardPropertiesPropertyIdIndexRoute =
  DashboardPropertiesPropertyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPropertiesPropertyIdRoute,
  } as any)
const DashboardPartnersPartnerIdIndexRoute =
  DashboardPartnersPartnerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPartnersPartnerIdRoute,
  } as any)
const DashboardInvestorsInvestorIdIndexRoute =
  DashboardInvestorsInvestorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInvestorsInvestorIdRoute,
  } as any)
const DashboardPropertiesPropertyIdEditRoute =
  DashboardPropertiesPropertyIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardPropertiesPropertyIdRoute,
  } as any)
const DashboardPartnersPartnerIdKycRoute =
  DashboardPartnersPartnerIdKycRouteImport.update({
    id: '/kyc',
    path: '/kyc',
    getParentRoute: () => DashboardPartnersPartnerIdRoute,
  } as any)
const DashboardInvestorsInvestorIdKycRoute =
  DashboardInvestorsInvestorIdKycRouteImport.update({
    id: '/kyc',
    path: '/kyc',
    getParentRoute: () => DashboardInvestorsInvestorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/account-type': typeof AccountTypeRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/signup-partner': typeof SignupPartnerRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/investors': typeof DashboardInvestorsRouteWithChildren
  '/dashboard/partners': typeof DashboardPartnersRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/investors/properties': typeof InvestorsPropertiesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/investors/': typeof InvestorsIndexRoute
  '/dashboard/investors/$investorId': typeof DashboardInvestorsInvestorIdRouteWithChildren
  '/dashboard/partners/$partnerId': typeof DashboardPartnersPartnerIdRouteWithChildren
  '/dashboard/properties/$propertyId': typeof DashboardPropertiesPropertyIdRouteWithChildren
  '/dashboard/properties/listed': typeof DashboardPropertiesListedRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/dashboard/transactions/payments': typeof DashboardTransactionsPaymentsRoute
  '/dashboard/transactions/receipts': typeof DashboardTransactionsReceiptsRoute
  '/dashboard/investors/': typeof DashboardInvestorsIndexRoute
  '/dashboard/partners/': typeof DashboardPartnersIndexRoute
  '/forgot-password/reset/': typeof ForgotPasswordResetIndexRoute
  '/dashboard/investors/$investorId/kyc': typeof DashboardInvestorsInvestorIdKycRoute
  '/dashboard/partners/$partnerId/kyc': typeof DashboardPartnersPartnerIdKycRoute
  '/dashboard/properties/$propertyId/edit': typeof DashboardPropertiesPropertyIdEditRoute
  '/dashboard/investors/$investorId/': typeof DashboardInvestorsInvestorIdIndexRoute
  '/dashboard/partners/$partnerId/': typeof DashboardPartnersPartnerIdIndexRoute
  '/dashboard/properties/$propertyId/': typeof DashboardPropertiesPropertyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-type': typeof AccountTypeRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/signup-partner': typeof SignupPartnerRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/investors/properties': typeof InvestorsPropertiesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/investors': typeof InvestorsIndexRoute
  '/dashboard/properties/listed': typeof DashboardPropertiesListedRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/dashboard/transactions/payments': typeof DashboardTransactionsPaymentsRoute
  '/dashboard/transactions/receipts': typeof DashboardTransactionsReceiptsRoute
  '/dashboard/investors': typeof DashboardInvestorsIndexRoute
  '/dashboard/partners': typeof DashboardPartnersIndexRoute
  '/forgot-password/reset': typeof ForgotPasswordResetIndexRoute
  '/dashboard/investors/$investorId/kyc': typeof DashboardInvestorsInvestorIdKycRoute
  '/dashboard/partners/$partnerId/kyc': typeof DashboardPartnersPartnerIdKycRoute
  '/dashboard/properties/$propertyId/edit': typeof DashboardPropertiesPropertyIdEditRoute
  '/dashboard/investors/$investorId': typeof DashboardInvestorsInvestorIdIndexRoute
  '/dashboard/partners/$partnerId': typeof DashboardPartnersPartnerIdIndexRoute
  '/dashboard/properties/$propertyId': typeof DashboardPropertiesPropertyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/account-type': typeof AccountTypeRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/signup-partner': typeof SignupPartnerRoute
  '/test': typeof TestRoute
  '/verify': typeof VerifyRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/investors': typeof DashboardInvestorsRouteWithChildren
  '/dashboard/partners': typeof DashboardPartnersRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/investors/properties': typeof InvestorsPropertiesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/investors/': typeof InvestorsIndexRoute
  '/dashboard/investors/$investorId': typeof DashboardInvestorsInvestorIdRouteWithChildren
  '/dashboard/partners/$partnerId': typeof DashboardPartnersPartnerIdRouteWithChildren
  '/dashboard/properties/$propertyId': typeof DashboardPropertiesPropertyIdRouteWithChildren
  '/dashboard/properties/listed': typeof DashboardPropertiesListedRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/dashboard/transactions/payments': typeof DashboardTransactionsPaymentsRoute
  '/dashboard/transactions/receipts': typeof DashboardTransactionsReceiptsRoute
  '/dashboard/investors/': typeof DashboardInvestorsIndexRoute
  '/dashboard/partners/': typeof DashboardPartnersIndexRoute
  '/forgot-password/reset/': typeof ForgotPasswordResetIndexRoute
  '/dashboard/investors/$investorId/kyc': typeof DashboardInvestorsInvestorIdKycRoute
  '/dashboard/partners/$partnerId/kyc': typeof DashboardPartnersPartnerIdKycRoute
  '/dashboard/properties/$propertyId/edit': typeof DashboardPropertiesPropertyIdEditRoute
  '/dashboard/investors/$investorId/': typeof DashboardInvestorsInvestorIdIndexRoute
  '/dashboard/partners/$partnerId/': typeof DashboardPartnersPartnerIdIndexRoute
  '/dashboard/properties/$propertyId/': typeof DashboardPropertiesPropertyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/account-type'
    | '/admin'
    | '/login'
    | '/otp'
    | '/signup'
    | '/signup-partner'
    | '/test'
    | '/verify'
    | '/dashboard/announcements'
    | '/dashboard/investors'
    | '/dashboard/partners'
    | '/dashboard/settings'
    | '/investors/properties'
    | '/dashboard/'
    | '/forgot-password/'
    | '/investors/'
    | '/dashboard/investors/$investorId'
    | '/dashboard/partners/$partnerId'
    | '/dashboard/properties/$propertyId'
    | '/dashboard/properties/listed'
    | '/dashboard/properties/new'
    | '/dashboard/transactions/payments'
    | '/dashboard/transactions/receipts'
    | '/dashboard/investors/'
    | '/dashboard/partners/'
    | '/forgot-password/reset/'
    | '/dashboard/investors/$investorId/kyc'
    | '/dashboard/partners/$partnerId/kyc'
    | '/dashboard/properties/$propertyId/edit'
    | '/dashboard/investors/$investorId/'
    | '/dashboard/partners/$partnerId/'
    | '/dashboard/properties/$propertyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-type'
    | '/admin'
    | '/login'
    | '/otp'
    | '/signup'
    | '/signup-partner'
    | '/test'
    | '/verify'
    | '/dashboard/announcements'
    | '/dashboard/settings'
    | '/investors/properties'
    | '/dashboard'
    | '/forgot-password'
    | '/investors'
    | '/dashboard/properties/listed'
    | '/dashboard/properties/new'
    | '/dashboard/transactions/payments'
    | '/dashboard/transactions/receipts'
    | '/dashboard/investors'
    | '/dashboard/partners'
    | '/forgot-password/reset'
    | '/dashboard/investors/$investorId/kyc'
    | '/dashboard/partners/$partnerId/kyc'
    | '/dashboard/properties/$propertyId/edit'
    | '/dashboard/investors/$investorId'
    | '/dashboard/partners/$partnerId'
    | '/dashboard/properties/$propertyId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/account-type'
    | '/admin'
    | '/login'
    | '/otp'
    | '/signup'
    | '/signup-partner'
    | '/test'
    | '/verify'
    | '/dashboard/announcements'
    | '/dashboard/investors'
    | '/dashboard/partners'
    | '/dashboard/settings'
    | '/investors/properties'
    | '/dashboard/'
    | '/forgot-password/'
    | '/investors/'
    | '/dashboard/investors/$investorId'
    | '/dashboard/partners/$partnerId'
    | '/dashboard/properties/$propertyId'
    | '/dashboard/properties/listed'
    | '/dashboard/properties/new'
    | '/dashboard/transactions/payments'
    | '/dashboard/transactions/receipts'
    | '/dashboard/investors/'
    | '/dashboard/partners/'
    | '/forgot-password/reset/'
    | '/dashboard/investors/$investorId/kyc'
    | '/dashboard/partners/$partnerId/kyc'
    | '/dashboard/properties/$propertyId/edit'
    | '/dashboard/investors/$investorId/'
    | '/dashboard/partners/$partnerId/'
    | '/dashboard/properties/$propertyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AccountTypeRoute: typeof AccountTypeRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  SignupRoute: typeof SignupRoute
  SignupPartnerRoute: typeof SignupPartnerRoute
  TestRoute: typeof TestRoute
  VerifyRoute: typeof VerifyRoute
  InvestorsPropertiesRoute: typeof InvestorsPropertiesRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  InvestorsIndexRoute: typeof InvestorsIndexRoute
  ForgotPasswordResetIndexRoute: typeof ForgotPasswordResetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-partner': {
      id: '/signup-partner'
      path: '/signup-partner'
      fullPath: '/signup-partner'
      preLoaderRoute: typeof SignupPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-type': {
      id: '/account-type'
      path: '/account-type'
      fullPath: '/account-type'
      preLoaderRoute: typeof AccountTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors/': {
      id: '/investors/'
      path: '/investors'
      fullPath: '/investors/'
      preLoaderRoute: typeof InvestorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/investors/properties': {
      id: '/investors/properties'
      path: '/investors/properties'
      fullPath: '/investors/properties'
      preLoaderRoute: typeof InvestorsPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/partners': {
      id: '/dashboard/partners'
      path: '/partners'
      fullPath: '/dashboard/partners'
      preLoaderRoute: typeof DashboardPartnersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/investors': {
      id: '/dashboard/investors'
      path: '/investors'
      fullPath: '/dashboard/investors'
      preLoaderRoute: typeof DashboardInvestorsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/forgot-password/reset/': {
      id: '/forgot-password/reset/'
      path: '/forgot-password/reset'
      fullPath: '/forgot-password/reset/'
      preLoaderRoute: typeof ForgotPasswordResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/partners/': {
      id: '/dashboard/partners/'
      path: '/'
      fullPath: '/dashboard/partners/'
      preLoaderRoute: typeof DashboardPartnersIndexRouteImport
      parentRoute: typeof DashboardPartnersRoute
    }
    '/dashboard/investors/': {
      id: '/dashboard/investors/'
      path: '/'
      fullPath: '/dashboard/investors/'
      preLoaderRoute: typeof DashboardInvestorsIndexRouteImport
      parentRoute: typeof DashboardInvestorsRoute
    }
    '/dashboard/transactions/receipts': {
      id: '/dashboard/transactions/receipts'
      path: '/transactions/receipts'
      fullPath: '/dashboard/transactions/receipts'
      preLoaderRoute: typeof DashboardTransactionsReceiptsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions/payments': {
      id: '/dashboard/transactions/payments'
      path: '/transactions/payments'
      fullPath: '/dashboard/transactions/payments'
      preLoaderRoute: typeof DashboardTransactionsPaymentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/properties/new': {
      id: '/dashboard/properties/new'
      path: '/properties/new'
      fullPath: '/dashboard/properties/new'
      preLoaderRoute: typeof DashboardPropertiesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/properties/listed': {
      id: '/dashboard/properties/listed'
      path: '/properties/listed'
      fullPath: '/dashboard/properties/listed'
      preLoaderRoute: typeof DashboardPropertiesListedRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/properties/$propertyId': {
      id: '/dashboard/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/dashboard/properties/$propertyId'
      preLoaderRoute: typeof DashboardPropertiesPropertyIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/partners/$partnerId': {
      id: '/dashboard/partners/$partnerId'
      path: '/$partnerId'
      fullPath: '/dashboard/partners/$partnerId'
      preLoaderRoute: typeof DashboardPartnersPartnerIdRouteImport
      parentRoute: typeof DashboardPartnersRoute
    }
    '/dashboard/investors/$investorId': {
      id: '/dashboard/investors/$investorId'
      path: '/$investorId'
      fullPath: '/dashboard/investors/$investorId'
      preLoaderRoute: typeof DashboardInvestorsInvestorIdRouteImport
      parentRoute: typeof DashboardInvestorsRoute
    }
    '/dashboard/properties/$propertyId/': {
      id: '/dashboard/properties/$propertyId/'
      path: '/'
      fullPath: '/dashboard/properties/$propertyId/'
      preLoaderRoute: typeof DashboardPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof DashboardPropertiesPropertyIdRoute
    }
    '/dashboard/partners/$partnerId/': {
      id: '/dashboard/partners/$partnerId/'
      path: '/'
      fullPath: '/dashboard/partners/$partnerId/'
      preLoaderRoute: typeof DashboardPartnersPartnerIdIndexRouteImport
      parentRoute: typeof DashboardPartnersPartnerIdRoute
    }
    '/dashboard/investors/$investorId/': {
      id: '/dashboard/investors/$investorId/'
      path: '/'
      fullPath: '/dashboard/investors/$investorId/'
      preLoaderRoute: typeof DashboardInvestorsInvestorIdIndexRouteImport
      parentRoute: typeof DashboardInvestorsInvestorIdRoute
    }
    '/dashboard/properties/$propertyId/edit': {
      id: '/dashboard/properties/$propertyId/edit'
      path: '/edit'
      fullPath: '/dashboard/properties/$propertyId/edit'
      preLoaderRoute: typeof DashboardPropertiesPropertyIdEditRouteImport
      parentRoute: typeof DashboardPropertiesPropertyIdRoute
    }
    '/dashboard/partners/$partnerId/kyc': {
      id: '/dashboard/partners/$partnerId/kyc'
      path: '/kyc'
      fullPath: '/dashboard/partners/$partnerId/kyc'
      preLoaderRoute: typeof DashboardPartnersPartnerIdKycRouteImport
      parentRoute: typeof DashboardPartnersPartnerIdRoute
    }
    '/dashboard/investors/$investorId/kyc': {
      id: '/dashboard/investors/$investorId/kyc'
      path: '/kyc'
      fullPath: '/dashboard/investors/$investorId/kyc'
      preLoaderRoute: typeof DashboardInvestorsInvestorIdKycRouteImport
      parentRoute: typeof DashboardInvestorsInvestorIdRoute
    }
  }
}

interface DashboardInvestorsInvestorIdRouteChildren {
  DashboardInvestorsInvestorIdKycRoute: typeof DashboardInvestorsInvestorIdKycRoute
  DashboardInvestorsInvestorIdIndexRoute: typeof DashboardInvestorsInvestorIdIndexRoute
}

const DashboardInvestorsInvestorIdRouteChildren: DashboardInvestorsInvestorIdRouteChildren =
  {
    DashboardInvestorsInvestorIdKycRoute: DashboardInvestorsInvestorIdKycRoute,
    DashboardInvestorsInvestorIdIndexRoute:
      DashboardInvestorsInvestorIdIndexRoute,
  }

const DashboardInvestorsInvestorIdRouteWithChildren =
  DashboardInvestorsInvestorIdRoute._addFileChildren(
    DashboardInvestorsInvestorIdRouteChildren,
  )

interface DashboardInvestorsRouteChildren {
  DashboardInvestorsInvestorIdRoute: typeof DashboardInvestorsInvestorIdRouteWithChildren
  DashboardInvestorsIndexRoute: typeof DashboardInvestorsIndexRoute
}

const DashboardInvestorsRouteChildren: DashboardInvestorsRouteChildren = {
  DashboardInvestorsInvestorIdRoute:
    DashboardInvestorsInvestorIdRouteWithChildren,
  DashboardInvestorsIndexRoute: DashboardInvestorsIndexRoute,
}

const DashboardInvestorsRouteWithChildren =
  DashboardInvestorsRoute._addFileChildren(DashboardInvestorsRouteChildren)

interface DashboardPartnersPartnerIdRouteChildren {
  DashboardPartnersPartnerIdKycRoute: typeof DashboardPartnersPartnerIdKycRoute
  DashboardPartnersPartnerIdIndexRoute: typeof DashboardPartnersPartnerIdIndexRoute
}

const DashboardPartnersPartnerIdRouteChildren: DashboardPartnersPartnerIdRouteChildren =
  {
    DashboardPartnersPartnerIdKycRoute: DashboardPartnersPartnerIdKycRoute,
    DashboardPartnersPartnerIdIndexRoute: DashboardPartnersPartnerIdIndexRoute,
  }

const DashboardPartnersPartnerIdRouteWithChildren =
  DashboardPartnersPartnerIdRoute._addFileChildren(
    DashboardPartnersPartnerIdRouteChildren,
  )

interface DashboardPartnersRouteChildren {
  DashboardPartnersPartnerIdRoute: typeof DashboardPartnersPartnerIdRouteWithChildren
  DashboardPartnersIndexRoute: typeof DashboardPartnersIndexRoute
}

const DashboardPartnersRouteChildren: DashboardPartnersRouteChildren = {
  DashboardPartnersPartnerIdRoute: DashboardPartnersPartnerIdRouteWithChildren,
  DashboardPartnersIndexRoute: DashboardPartnersIndexRoute,
}

const DashboardPartnersRouteWithChildren =
  DashboardPartnersRoute._addFileChildren(DashboardPartnersRouteChildren)

interface DashboardPropertiesPropertyIdRouteChildren {
  DashboardPropertiesPropertyIdEditRoute: typeof DashboardPropertiesPropertyIdEditRoute
  DashboardPropertiesPropertyIdIndexRoute: typeof DashboardPropertiesPropertyIdIndexRoute
}

const DashboardPropertiesPropertyIdRouteChildren: DashboardPropertiesPropertyIdRouteChildren =
  {
    DashboardPropertiesPropertyIdEditRoute:
      DashboardPropertiesPropertyIdEditRoute,
    DashboardPropertiesPropertyIdIndexRoute:
      DashboardPropertiesPropertyIdIndexRoute,
  }

const DashboardPropertiesPropertyIdRouteWithChildren =
  DashboardPropertiesPropertyIdRoute._addFileChildren(
    DashboardPropertiesPropertyIdRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardInvestorsRoute: typeof DashboardInvestorsRouteWithChildren
  DashboardPartnersRoute: typeof DashboardPartnersRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPropertiesPropertyIdRoute: typeof DashboardPropertiesPropertyIdRouteWithChildren
  DashboardPropertiesListedRoute: typeof DashboardPropertiesListedRoute
  DashboardPropertiesNewRoute: typeof DashboardPropertiesNewRoute
  DashboardTransactionsPaymentsRoute: typeof DashboardTransactionsPaymentsRoute
  DashboardTransactionsReceiptsRoute: typeof DashboardTransactionsReceiptsRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardInvestorsRoute: DashboardInvestorsRouteWithChildren,
  DashboardPartnersRoute: DashboardPartnersRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPropertiesPropertyIdRoute:
    DashboardPropertiesPropertyIdRouteWithChildren,
  DashboardPropertiesListedRoute: DashboardPropertiesListedRoute,
  DashboardPropertiesNewRoute: DashboardPropertiesNewRoute,
  DashboardTransactionsPaymentsRoute: DashboardTransactionsPaymentsRoute,
  DashboardTransactionsReceiptsRoute: DashboardTransactionsReceiptsRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AccountTypeRoute: AccountTypeRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  SignupRoute: SignupRoute,
  SignupPartnerRoute: SignupPartnerRoute,
  TestRoute: TestRoute,
  VerifyRoute: VerifyRoute,
  InvestorsPropertiesRoute: InvestorsPropertiesRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  InvestorsIndexRoute: InvestorsIndexRoute,
  ForgotPasswordResetIndexRoute: ForgotPasswordResetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
