/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPartnersRouteImport } from './routes/dashboard/partners'
import { Route as DashboardInvestorsRouteImport } from './routes/dashboard/investors'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard/announcements'
import { Route as DashboardTransactionsReceiptsRouteImport } from './routes/dashboard/transactions/receipts'
import { Route as DashboardTransactionsPaymentsRouteImport } from './routes/dashboard/transactions/payments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPartnersRoute = DashboardPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvestorsRoute = DashboardInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsReceiptsRoute =
  DashboardTransactionsReceiptsRouteImport.update({
    id: '/transactions/receipts',
    path: '/transactions/receipts',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTransactionsPaymentsRoute =
  DashboardTransactionsPaymentsRouteImport.update({
    id: '/transactions/payments',
    path: '/transactions/payments',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/investors': typeof DashboardInvestorsRoute
  '/dashboard/partners': typeof DashboardPartnersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/transactions/payments': typeof DashboardTransactionsPaymentsRoute
  '/dashboard/transactions/receipts': typeof DashboardTransactionsReceiptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/investors': typeof DashboardInvestorsRoute
  '/dashboard/partners': typeof DashboardPartnersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/transactions/payments': typeof DashboardTransactionsPaymentsRoute
  '/dashboard/transactions/receipts': typeof DashboardTransactionsReceiptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/investors': typeof DashboardInvestorsRoute
  '/dashboard/partners': typeof DashboardPartnersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/transactions/payments': typeof DashboardTransactionsPaymentsRoute
  '/dashboard/transactions/receipts': typeof DashboardTransactionsReceiptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/announcements'
    | '/dashboard/investors'
    | '/dashboard/partners'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/transactions/payments'
    | '/dashboard/transactions/receipts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/dashboard/announcements'
    | '/dashboard/investors'
    | '/dashboard/partners'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/transactions/payments'
    | '/dashboard/transactions/receipts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/announcements'
    | '/dashboard/investors'
    | '/dashboard/partners'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/transactions/payments'
    | '/dashboard/transactions/receipts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners': {
      id: '/dashboard/partners'
      path: '/partners'
      fullPath: '/dashboard/partners'
      preLoaderRoute: typeof DashboardPartnersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/investors': {
      id: '/dashboard/investors'
      path: '/investors'
      fullPath: '/dashboard/investors'
      preLoaderRoute: typeof DashboardInvestorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions/receipts': {
      id: '/dashboard/transactions/receipts'
      path: '/transactions/receipts'
      fullPath: '/dashboard/transactions/receipts'
      preLoaderRoute: typeof DashboardTransactionsReceiptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions/payments': {
      id: '/dashboard/transactions/payments'
      path: '/transactions/payments'
      fullPath: '/dashboard/transactions/payments'
      preLoaderRoute: typeof DashboardTransactionsPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardInvestorsRoute: typeof DashboardInvestorsRoute
  DashboardPartnersRoute: typeof DashboardPartnersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTransactionsPaymentsRoute: typeof DashboardTransactionsPaymentsRoute
  DashboardTransactionsReceiptsRoute: typeof DashboardTransactionsReceiptsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardInvestorsRoute: DashboardInvestorsRoute,
  DashboardPartnersRoute: DashboardPartnersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTransactionsPaymentsRoute: DashboardTransactionsPaymentsRoute,
  DashboardTransactionsReceiptsRoute: DashboardTransactionsReceiptsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
